name: goodvibesofficial
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.3
  flutter_svg_provider: ^0.1.8
  simple_animations: ^3.0.3
  align_positioned: ^2.0.0
  responsive_flutter: ^0.0.4
  connectivity: ^3.0.3
  equatable: ^1.2.5
  provider: ^4.0.5
  get_it: ^4.0.2
  rxdart: ^0.24.0
  flutter_bloc: ^6.1.0

  #utils
  sqflite: any
  shared_preferences: ^0.5.7+3
  dio: any
  cached_network_image: ^2.3.3
  app_settings: ^4.0.1+1
  intl: ^0.16.0
  url_launcher: ^5.1.4
  image_picker: ^0.6.1+4
  flutter_html: ^0.11.1
  flutter_webview_plugin: ^0.3.9+1
  flutter_email_sender: ^3.0.1
  path_provider:
  package_info:
  device_info: ^0.4.2
  flutter_share: ^1.0.2+1
  share: ^0.6.5+2
  characters:
  flutter_ffmpeg: ^0.2.10


  #ui
  fluttertoast: ^4.0.1
  sleek_circular_slider:
  carousel_slider: ^2.0.0
  jiffy: ^3.0.1
  lazy_load_scrollview: ^1.1.0
  device_preview:
  flutter_spinkit:
  logger:
  shimmer:
  flutter_screenutil: ^2.3.1
  flutter_vector_icons:
  material_design_icons_flutter: ^4.0.5955
  responsive_grid: ^1.1.1
  modal_progress_hud: ^0.1.3
  country_pickers: ^1.3.0
  pull_to_refresh: ^1.6.2
  simple_gravatar: ^1.0.5
  dio_http_cache: ^0.2.8
  pin_code_fields: ^7.0.0
  dotted_line: ^3.0.0



  flutter_downloader: ^1.5.2

  #firebase and related
  firebase_crashlytics: ^0.2.3
  dio_firebase_performance:

  version:
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/new gradient2.svg
    - assets/images/loginbg.png
    - assets/images/bg@3x.png
    - assets/images/Icon simple-google.svg
    - assets/images/Icon awesome-facebook-f.svg
    - assets/images/timothee-duran-ilfsT5p_qvA-unsplash.png
    - assets/images/Icon simple-google.png
    - assets/images/Icon feather-mail.svg
    - assets/images/fgpwbg.png
    - assets/images/blurredbg.png
    - assets/images/forgot-2.svg
    - assets/images/otp.svg
    - assets/images/vincent-guth-gD7KrKqYZFk-unsplash.png
    - assets/images/reset.svg
    - assets/images/logo 2.svg
    - assets/images/goalsbg.png
    - assets/images/profile@3x.png
    - assets/images/home copy.svg
    - assets/images/noun_Library_2005386.svg
    - assets/images/anxiety.png
    - assets/images/calm.png
    - assets/images/stressicon.png
    - assets/images/stress icon@2x.png
    - assets/images/sleep icon@3x.png
    - assets/images/illustration@3x.png
    - assets/images/illustration@2x.png
    - assets/images/candle.png
    - assets/images/medi.png
    - assets/images/lotus@3x.png
    - assets/images/bannerimage and text@3x.png
    - assets/images/lotusmeditatebg.png
    - assets/images/anxietybg.png
    - assets/images/calmbg.png
    - assets/images/stressbg.png
    - assets/images/sleeppbg.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helveticaneuebold
      fonts:
        - asset: assets/fonts/Helvetica Neu Bold.ttf
    - family: Helveticaneuemedium
      fonts:
        - asset: assets/fonts/HelveticaNeue Medium.ttf
    - family: Helveticaneuethin
      fonts:
        - asset: assets/fonts/HelveticaNeue Thin.ttf
    - family: Helveticaneueregular
      fonts:
        - asset: assets/fonts/HELR45W.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
