name: goodvibesoffl
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #state manageement
  equatable: ^1.2.5
  provider: ^4.0.5
  get_it: ^7.0.0
  rxdart: ^0.24.0
  flutter_bloc: ^6.1.0
  #utils
  sqflite: any
  connectivity: ^0.4.4
  shared_preferences: ^0.5.7+3
  dio: any
  cached_network_image: ^2.3.3
  app_settings: ^4.0.1+1
  intl: ^0.16.0
  url_launcher: ^5.1.4
  image_picker: ^0.6.1+4
  flutter_html: ^0.11.1
  flutter_webview_plugin: ^0.3.9+1
  flutter_email_sender: ^3.0.1
  path_provider:
  package_info:
  device_info: ^0.4.2
  flutter_share: ^1.0.2+1
  share: ^0.6.5+2
  characters:
  flutter_ffmpeg: ^0.2.10
  version:
  # firebase and related
  firebase_core:
  cloud_firestore: ^0.14.0
  firebase_dynamic_links: ^0.6.2
  firebase_performance: ^0.4.2
  firebase_in_app_messaging: ^0.2.0+1
  flutter_local_notifications: ^1.4.4
  dio_firebase_performance:
  google_api_availability: ^2.0.4
  flutter_native_admob: ^2.1.0
  firebase_admob: ^0.10.1
  firebase_messaging: ^6.0.16
  firebase_remote_config: ^0.3.0+3
  google_sign_in: ^4.0.7
  flutter_facebook_auth: ^1.0.2+2


  #ui
  ionicons: ^0.1.2
  font_awesome_flutter: ^9.0.0
  audio_video_progress_bar: ^0.4.0
  cupertino_icons: ^1.0.2
  fluttertoast: ^4.0.1
  sleek_circular_slider:
  responsive_flutter: ^0.0.4
  carousel_slider: ^2.0.0
  jiffy: ^3.0.1
  lazy_load_scrollview: ^1.1.0
  device_preview:
  flutter_spinkit:
  logger:
  flutter_svg: ^0.18.0
  shimmer:
  flutter_screenutil: ^2.3.1
  flutter_vector_icons:
  responsive_grid: ^1.1.1
  modal_progress_hud: ^0.1.3
  country_pickers: ^1.3.0
  pull_to_refresh: ^1.6.2
  simple_gravatar: ^1.0.5
  dio_http_cache: ^0.2.8
  webview_flutter: ^2.0.4
  sliding_up_panel: ^2.0.0+1
  simple_animations: ^3.0.3
  material_design_icons_flutter: ^4.0.5955
  flutter_slidable: ^0.6.0
  pin_code_fields: ^7.0.0
  email_validator: ^2.0.1
  feather_icons: ^1.0.1
  swipedetector: ^1.2.0
  flutter_facebook_login: ^3.0.0

  assets_audio_player: ^2.0.13+1

  flutter_downloader: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/2 Minute Timer - Calm and Relaxing Music.mp3


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helveticaneuebold
      fonts:
        - asset: assets/fonts/Helvetica Neu Bold.ttf
    - family: Helveticaneuemedium
      fonts:
        - asset: assets/fonts/HelveticaNeue Medium.ttf
    - family: Helveticaneuethin
      fonts:
        - asset: assets/fonts/HelveticaNeue Thin.ttf
    - family: Helveticaneueregular
      fonts:
        - asset: assets/fonts/HELR45W.ttf
    - family: Sfprothin
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
    - family: Sfproregular
      fonts:
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Regular.ttf
    - family: Sfprosemibold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
