name: goodvibesofficial
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.3
  flutter_svg_provider: ^0.1.8
  simple_animations: ^3.0.3
  responsive_flutter: ^0.0.4
  connectivity: ^3.0.3
  equatable: ^1.2.5
  provider: ^4.0.5
  get_it: ^4.0.2
  rxdart: ^0.24.0
  flutter_bloc: ^6.1.0

  #utils
  sqflite: any
  shared_preferences: ^0.5.7+3
  dio: any
  cached_network_image: ^2.3.3
  app_settings: ^4.0.1+1
  intl: ^0.16.0
  url_launcher: ^5.1.4
  flutter_html: ^0.11.1
  path_provider:
  http: ^0.13.1



  #ui
  fluttertoast: ^4.0.1
  sleek_circular_slider:
  flutter_vector_icons:
  material_design_icons_flutter: ^4.0.5955
  pin_code_fields: ^7.0.0
  audio_video_progress_bar: ^0.3.0
  liquid_progress_indicator: ^0.3.2
  flutter_staggered_grid_view: ^0.3.4
  flutter_downloader: ^1.5.2
  flutter_feather_icons: ^2.0.0+1
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  flutter_slidable: ^0.6.0


  #firebase and related
  dio_firebase_performance:
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.5
  shimmer: ^2.0.0



  version:
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/bg@3x.png
    - assets/images/timothee-duran-ilfsT5p_qvA-unsplash.png
    - assets/images/blurredbg.png
    - assets/images/forgot-2.svg
    - assets/images/otp.svg
    - assets/images/reset.svg
    - assets/images/logo 2.svg
    - assets/images/goalsbg.png
    - assets/images/profile@3x.png
    - assets/images/home copy.svg
    - assets/images/noun_Library_2005386.svg
    - assets/images/anxiety.png
    - assets/images/calm.png
    - assets/images/stressicon.png
    - assets/images/stress icon@2x.png
    - assets/images/sleep icon@3x.png
    - assets/images/illustration@3x.png
    - assets/images/illustration@2x.png
    - assets/images/candle.png
    - assets/images/medi.png
    - assets/images/lotus@3x.png
    - assets/images/bannerimage and text@3x.png
    - assets/images/lotusmeditatebg.png
    - assets/images/anxietybg.png
    - assets/images/calmbg.png
    - assets/images/stressbg.png
    - assets/images/sleeppbg.png
    - assets/images/premcont.png
    - assets/images/user copy@3x.png
    - assets/images/user copy.svg
    - assets/images/profileicon.png
    - assets/images/intrographicsbg.png
    - assets/images/casual-life-3d-meditation-1@3x.png
    - casual-life-theotherone.png
    - assets/images/shuffle.svg
    - assets/images/timer.svg
    - assets/images/pexels-pixabay-355209.jpg
    - assets/images/pexels-karolina-grabowska-4203102.jpg
    - assets/images/pexels-hoang-loc-1905054.jpg
    - assets/images/pexels-maël-balland-3099153.jpg
    - assets/images/purple circle@2x.png
    - assets/images/orange_circle.png
    - assets/images/background_latest@2x.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helveticaneuebold
      fonts:
        - asset: assets/fonts/Helvetica Neu Bold.ttf
    - family: Helveticaneuemedium
      fonts:
        - asset: assets/fonts/HelveticaNeue Medium.ttf
    - family: Helveticaneuethin
      fonts:
        - asset: assets/fonts/HelveticaNeue Thin.ttf
    - family: Helveticaneueregular
      fonts:
        - asset: assets/fonts/HELR45W.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
